package com.np.schoolpgi.constants;

public enum EventListEnum {

	//HOME CONTROLLER
	FORGOT_PASSWORD(1, "FORGOT PASSWPRD"),
	VALIDATE_OTP(2, "VALIDATE OTP"),
	RESET_PASSWORD(3, "RESET PASSWORD"),
	UPDATE_PASSWORD(4, "UPDATE PASSWORD"),
	
	CREATE_ROLE(5, "CREATE ROLE"),
	VIEW_ROLE(6, "VIEW ROLE"),
	UPDATE_ROLE(7, "UPDATE ROLE"),
	DELETE_ROLE(8, "DELETE ROLE"),
	
	MANAGE_SETTING(9, "MANAGE_SETTING"),
	SAVE_SETTING(10, "SAVE SETTING"),
	MENU_LIST(11, "MENU LIST"),
	
	CREATE_LEVEL(12, "CREATE LEVEL"),
	UPDATE_LEVEL(13, "UPDATE LEVEL"),
	VIEW_LEVEL(14, "VIEW_LEVEL"),
	DELETE_LEVEL(15, "DELETE LEVEL"),
	
	CHILD_LEVEL(16, "CHILD LEVEL"),
	VIEW_BLOCK_LEVEL_INSTANCE(17, "VIEW BLOCK LEVEL INSTANCE"),
	CREATE_SCHOOL(18, "CREATE SCHOOL"),
	UPDATE_SCHOOL(19, "UPDATE SCHOOL"),
	VIEW_SCHOOL(20, "VIEW SCHOOL"),
	DELETE_SCHOOL(21, "DELETE SCHOOL"),
	
	CREATE_DOMAIN(22, "CREATE DOMAIN"),
	UPDATE_DOMAIN(23, "UPDATE DOMAIN"),
	VIEW_DOMAIN(24, "VIEW DOMAIN"),
	DELETE_DOMAIN(25, "DELETE DOMAIN"),
	
	CREATE_INSTANCE(26, "CREATE INSTANCE"),
	VIEW_INSTANCES(27, "VIEW INSTANCES"),
	DELETE_INSTANCE(28, "DELETE INSTANCE"),
	UPDATE_INSTANCE(29, "UPDATE INSTANCE"),
	
	CREATE_SUB_DOMAIN(30, "CREATE SUB DOMAIN"),
	UPDATE_SUB_DOMAIN(31, "CREATE SUB DOMAIN"),
	VIEW_SUB_DOMAIN(32, "VIEW SUB DOMAIN"),
	DELETE_SUB_DOMAIN(33, "DELETE SUB DOMAIN"),
	
	CREATE_DATA_SOURCE(34, "CREATE DATA SOURCE"),
	UPDATE_DATA_SOURCE(35, "UPDATE DATA SOURCE"),
	VIEW_DATA_SOURCE(36, "VIEW DATA SOURCE"),
	DELETE_DATA_SOURCE(37, "DELETE_DATA_SOURCE"),
	
	VIEW_QUESTION_TYPE(38, "VIEW QUESTION TYPE"),
	CREATE_QUESTION(39, "CREATE QUESTION"),
	UPDATE_QUESTION(40, "UPDATE QUESTION"),
	VIEW_QUESTION(41, "VIEW QUESTION"),
	DELETE_QUESTION(42, "DELETE QUESTION"),
	
	CREATE_SUB_QUESTION(43, "CREATE SUB QUESTION"),
	UPDATE_SUB_QUESTION(44, "UPDATE SUB QUESTION"),
	VIEW_SUB_QUESTION(45, "VIEW SUB QUESTION"),
	DELETE_SUB_QUESTION(46, "DELETE QUESTION"),
	
	CREATE_USER(47, "CREATE USER"),
	VIEW_USER(48, "VIEW USER"),
	UPDATE_USER(49, "UPDATE USER"),
	DELETE_USER(50, "DELETE USER"),
	
	VIEW_EVENT_LOGS(51, "VIEW EVENT LOGS"),
	
	VIEW_NOTIFICATIONS(52, "VIEW NOTIFICATIONS"),
	
	MARK_NOTIFICATION_AS_READUNREAD(53, "MARK NOTIFICATION AS READUNREAD"),
	
	YEARS_LIST(54, "YEARS LIST"),
	CREATE_SURVEY(55, "CREATE SURVEY"),
	UPDATE_SURVEY(56, "UPDATE SURVEY"),
	SURVEY_LIST(57, "SURVEY LIST"),
	DELETE_SURVEY(58, "DELETE SURVEY"),
	USER_SURVEY_LIST(59, "USER SURVEY LIST"),
	
	
	CREATE_SURVEY_MAP_QUEST(60, "CREATE SURVEY MAP QUEST"),
	VIEW_SURVEY_MAP_QUEST(61, "VIEW SURVEY MAP QUEST"),
	SURVEY_SUB_QUEST_BY_QUEST_ID(62, "SURVEY SUB QUEST BY QUEST ID"),
	UPDATE_SURVEY_MAP_QUEST(63, "UPDATE SURVEY MAP QUEST"),
	DELETE_SURVEY_MAP_QUEST(64, "DELETE SURVEY MAP QUEST"),
	
//	GET_UPD_SURVEY_SUMMARY_ACTION_G(65, "GET UPD SURVEY SUMMARY FOR ACTION G"),
	
//	GET_UPD_SURVEY_SUMMARY_ACTION_U(67, "GET UPD SURVEY SUMMARY FOR ACTION U"),
	
	SURVEY_DATA_ENTRY_BY_ID(68, "SURVEY DATA ENTRY BY ID"),
	SURVEY_DEO_LIST(69, "SURVEY DATA ENTRY LIST"),
	
	S_INSERT_SURVEY_DATA_ENTRY(70, "INSERT SURVEY DATA ENTRY - SAVE"),
	C_INSERT_SURVEY_DATA_ENTRY(71, "INSERT SURVEY DATA ENTRY - SAVE AND SUBMIT"),
	CLONE_SURVEY(72, "CLONE SURVEY"),
	
	DOWNLOAD_SURVEY_EXCEL(73, "DOWNLOAD SURVEY EXCEL"),
	UPLOAD_SURVEY_EXCEL(74, "UPLOAD SURVEY EXCEL"),
	
	//AuthController
	
	LOGIN(75, "LOGIN"),
	REFRESH_TOKEN(76, "REFRESH TOKEN"),
	
	//MediaUploadController
	
	MEDIA_UPLOAD(77, "MEDIA UPLOAD"),
	MEDIA_CATEGORY(78, "MEDIA CATEGORY"),
	DELETE_FILE(79, "DELETE UPLOADED FILE"),
//	FILES(79, "VIEW FILES"),
	
	//SurveyAssignUnAssignController
	
	AST_ASSIGN_UNASSIGN_SURVEY(80, "ASSIGN UNASSIGN SURVEY - ASSIGN"),
	UST_ASSIGN_UNASSIGN_SURVEY(81, "ASSIGN UNASSIGN SURVEY - UN ASSIGN"),
	NOTIFY_SURVEY(82, "NOTIFY SURVEY"),
	
	//SurveyReviewController
	
	GET_REAMRKS(83, "GET REMARKS"),
	SURVEY_DATA_LIST_REVIEW(84, "SURVEY DATA LIST REVIEW"),
	SURVEY_DATA_LIST_REVIEW_DETAILS(85, "SURVEY DATA LIST REVIEW DETAILS"),
	RV_UPDATE_SURVEY_REVIEW_APPROVE(86, "UPDATE SURVEY REVIEW APPROVE - REVIEWED"),
	RE_UPDATE_SURVEY_REVIEW_APPROVE(87, "UPDATE SURVEY REVIEW APPROVE - REQUEST TO EDIT FOR REVIEW"),
	AP_UPDATE_SURVEY_REVIEW_APPROVE(88, "UPDATE SURVEY REVIEW APPROVE - APPROVED"),
	AE_UPDATE_SURVEY_REVIEW_APPROVE(89, "UPDATE SURVEY REVIEW APPROVE - REQUEST TO EDIT APPROVE");
	

	Integer eventId = null;
	String eventName = null;
	
	private EventListEnum(Integer eventId, String eventName) {
		this.eventId=eventId;
		this.eventName=eventName;
	}
	
	public Integer getEventId() {
		return eventId;
	}
	public String getEventName() {
		return eventName;
	}
	
}
